SET NOCOUNT ON
USE dev
GO

IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.usp_delete_empleados') AND SYSSTAT & 0xf = 4)
	DROP PROCEDURE dbo.usp_delete_empleados
GO

CREATE PROCEDURE usp_delete_empleados
	@ID INT
AS 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DELETE FROM Empleados WHERE ClaveEmpleado = @ID
